name: Run TypeScript with TSX on Main Branch

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # You can change this to your preferred Node.js version.

      - name: Install Dependencies
        run: npm install # You should have a package.json with your dependencies.

      - name: Generate JSON Files
        env:
          VITE_APP_MAPBOX_KEY: ${{ secrets.VITE_APP_MAPBOX_KEY }}
          GTFS_URLS: ${{ secrets.GTFS_URL }}

        run: npm run gtfs
